# Network Planning Service Configuration v3.1
server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

scheduling:
  external_api: "https://schedules.prod.iaros.ai"
  retry_interval: "2s"
  max_retries: 3

codeshare:
  external_api: "https://partners.prod.iaros.ai/codeshares"
  discrepancy_threshold: 5
  fallback_cache: true

logging:
  level: "INFO"
  format: "json"
  output: "stdout"

monitoring:
  alert_threshold: 90
