# azure-pipelines.yml - Alternative CI/CD configuration using Azure DevOps.
trigger:
  branches:
    include:
      - main
jobs:
- job: BuildAndTest
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      docker-compose build
      ./run_tests.sh
    displayName: 'Build and Run Tests'
- job: Deploy
  dependsOn: BuildAndTest
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      ./k8s-deploy.sh
    displayName: 'Deploy to Kubernetes'
