# sample_canary_test.yaml
name: "IAROS API Canary Test"
description: "Simulates a key transaction to ensure API responsiveness and proper fallback activation."
steps:
  - http:
      url: "https://api.iaros.ai/healthcheck"
      method: "GET"
      expected_status: 200
  - wait: 30s
  - http:
      url: "https://api.iaros.ai/pricing"
      method: "GET"
      expected_status: 200
