# forecasting-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecasting-service
  namespace: iaros-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forecasting-service
  template:
    metadata:
      labels:
        app: forecasting-service
    spec:
      containers:
      - name: forecasting-service
        image: iaros/forecasting-service:v4.0
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: "600m"
            memory: "1Gi"
          requests:
            cpu: "300m"
            memory: "512Mi"
