# Offer Service Configuration v3.1
server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

offer:
  personalization:
    loyalty_multiplier: 0.95
  fallback:
    use_cached_offer: true
    cache_expiry: "5m"

logging:
  level: "INFO"
  format: "json"
  output: "stdout"

endpoints:
  pricing_service: "http://pricing_service:8080"
  forecasting_service: "http://forecasting_service:8081"
  ancillary_service: "http://ancillary_service:8082"
