# k8s_audit_policies.yaml
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: Metadata
    verbs: ["create", "update", "delete"]
    resources:
      - group: ""
        resources: ["pods", "services", "deployments"]
    omitStages:
      - RequestReceived
