# calico_config.yaml
apiVersion: projectcalico.org/v3
kind: Installation
metadata:
  name: default
spec:
  variant: Calico
  calicoNetwork:
    bgp: Enabled
    ipPools:
    - cidr: 192.168.0.0/16
      encapsulation: IPIP
      natOutgoing: true
      disabled: false
