openapi: "3.0.1"
info:
  title: IAROS Public API
  version: "v3.0.0"
  description: "Public API specification for IAROS endpoints, including dynamic pricing, forecasting, and offer management."
servers:
  - url: "https://api.iaros.ai"
paths:
  /pricing:
    get:
      summary: "Retrieve dynamic pricing data"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: number
                    format: float
  /forecast:
    get:
      summary: "Retrieve forecast data"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  forecast:
                    type: array
                    items:
                      type: number
