# deployment_strategy.yaml
# 5-phase Canary Deployment Rollout Strategy
phases:
  - phase: "Phase 1 - Internal Testing"
    percentage: 5
    duration: "1h"
  - phase: "Phase 2 - Pilot Rollout"
    percentage: 15
    duration: "2h"
  - phase: "Phase 3 - Gradual Rollout"
    percentage: 30
    duration: "4h"
  - phase: "Phase 4 - Majority Deployment"
    percentage: 70
    duration: "6h"
  - phase: "Phase 5 - Full Rollout"
    percentage: 100
    duration: "Continuous"
