# Pricing Service Configuration v3.1
server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

pricing:
  base_fares:
    IN-EM: 100.0
    EM-US: 150.0
  adjustments:
    geo_fencing:
      IN: 0.85
    corporate:
      sensitivity: 0.02
    event_surge:
      threshold: 0.8
      multiplier: 1.2

fallback:
  use_cached_price: true
  cache_expiry: "5m"
  historical_average_fallback: true
  historical_window: "7d"

logging:
  level: "INFO"
  format: "json"
  output: "stdout"

endpoints:
  forecasting_service: "http://forecasting_service:8081"
  ancillary_service: "http://ancillary_service:8082"

circuit_breaker:
  timeout: 2000
  max_concurrent_requests: 100
  error_percent_threshold: 25
