# Customer Intelligence Platform Configuration

# Server configuration
server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  max_header_bytes: 1048576

# Database configuration
database:
  mongodb:
    uri: "mongodb://mongodb:27017"
    database: "customer_intelligence"
    timeout: "10s"
    max_pool_size: 100
    min_pool_size: 10

# Redis cache configuration
cache:
  redis:
    addr: "redis:6379"
    password: ""
    db: 0
    pool_size: 20
    min_idle_conns: 5
    dial_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"

# Kafka configuration for real-time events
kafka:
  brokers: ["kafka:9092"]
  topics:
    customer_events: "customer.events"
    profile_updates: "customer.profile.updates"
    segmentation_updates: "customer.segmentation.updates"
  consumer_group: "customer-intelligence-platform"
  batch_size: 1000
  batch_timeout: "1s"

# Customer Intelligence configuration
intelligence:
  # Profile enrichment settings
  profile:
    max_data_sources: 25
    enrichment_accuracy_threshold: 0.995
    identity_resolution_threshold: 0.95
    data_retention_days: 2555
    
  # Segmentation settings
  segmentation:
    max_segments: 500
    ml_models_count: 50
    segment_refresh_interval: "5m"
    rfm_calculation_window: "365d"
    behavioral_window: "90d"
    
  # Scoring settings
  scoring:
    real_time_timeout: "1s"
    batch_processing_interval: "5m"
    model_retrain_interval: "24h"
    propensity_threshold: 0.7
    
  # Competitive intelligence
  competitive:
    price_update_interval: "15m"
    competitor_sources: 5
    data_quality_threshold: 0.9
    trend_analysis_window: "30d"

# Data sources configuration
data_sources:
  # PSS integration
  pss:
    endpoint: "http://pss-service:8080"
    timeout: "10s"
    retry_attempts: 3
    
  # CRM integration
  crm:
    endpoint: "http://crm-service:8080"
    timeout: "5s"
    retry_attempts: 3
    
  # Web analytics
  web_analytics:
    endpoint: "http://analytics-service:8080"
    timeout: "5s"
    batch_size: 1000
    
  # Mobile SDK
  mobile_sdk:
    endpoint: "http://mobile-analytics:8080"
    timeout: "5s"
    event_buffer_size: 5000
    
  # External enrichment
  external:
    demographics_api: "https://api.demographics.com"
    credit_segment_api: "https://api.creditsegments.com"
    timeout: "10s"
    rate_limit: 1000

# Machine Learning configuration
ml:
  models:
    # Segmentation models
    kmeans_clusters: 10
    rfm_segments: 8
    behavioral_segments: 12
    
    # Propensity models
    booking_propensity: "xgboost"
    ancillary_propensity: "random_forest"
    cross_sell_propensity: "neural_network"
    
    # Model training
    train_data_split: 0.8
    validation_split: 0.1
    test_split: 0.1
    max_training_time: "2h"
    
  feature_store:
    refresh_interval: "1h"
    feature_retention: "90d"
    max_features: 500

# Privacy and compliance
privacy:
  gdpr_compliance: true
  ccpa_compliance: true
  data_anonymization: true
  consent_required: true
  audit_trail: true
  
  # Encryption settings
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    
  # Data subject rights
  data_subject_rights:
    access_timeout: "72h"
    portability_timeout: "30d"
    erasure_timeout: "30d"

# Security configuration
security:
  jwt:
    secret: "customer-intelligence-jwt-secret"
    expiry: "24h"
    
  rate_limiting:
    requests_per_minute: 1000
    burst_size: 100
    
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]

# Monitoring and observability
monitoring:
  # Metrics
  metrics:
    enabled: true
    endpoint: "/metrics"
    interval: "15s"
    
  # Health checks
  health:
    endpoint: "/health"
    timeout: "5s"
    
  # Logging
  logging:
    level: "info"
    format: "json"
    output: "stdout"
    
  # Tracing
  tracing:
    enabled: true
    jaeger_endpoint: "http://jaeger:14268/api/traces"
    sample_rate: 0.1

# Performance optimization
performance:
  # Connection pooling
  connection_pools:
    max_connections: 100
    max_idle_connections: 10
    connection_max_lifetime: "1h"
    
  # Caching
  caching:
    profile_cache_ttl: "1h"
    segment_cache_ttl: "30m"
    score_cache_ttl: "15m"
    
  # Batch processing
  batch_processing:
    max_batch_size: 1000
    batch_timeout: "5s"
    worker_count: 10

# Feature flags
features:
  real_time_scoring: true
  competitive_intelligence: true
  behavioral_segmentation: true
  external_enrichment: true
  ml_auto_retrain: true
  gdpr_auto_deletion: true

# Environment-specific overrides
environment: "production"

# Development settings (only used in dev environment)
development:
  debug_mode: false
  mock_external_apis: false
  sample_data_enabled: false 