fallback_strategies:
  geo_fencing:
    ttl: 30m
    refresh_interval: 5m
    max_staleness: 1h
  historical:
    window_sizes: [24h, 7d, 30d]
    drift_threshold: 15%
  static_floor:
    iata_compliance: true
    regional_markups:
      NA: 15%
      EU: 12%
      APAC: 18%
