# API Gateway Configuration v3.1
# Validated by InfoSec Team - YYYY-MM-DD

environments:
  production:
    listener:
      port: 8443
      tls:
        min_version: "1.3"
        ciphers: "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"
      rate_limit:
        global: 10000 RPM
        per_ip: 500 RPM
        burst: 100
      circuit_breakers:
        pricing_service:
          threshold: "45% error rate (5m window)"
          fallback: "cached_pricing_v2"
          retry_policy:
            strategy: "exponential_backoff"
            max_attempts: 3
            initial_delay: 100ms
        forecasting_service:
          threshold: "30% latency >500ms"
          fallback: "historical_seasonal_data"
  staging:
    features:
      chaos_injection: true
      debug_endpoints: true
    testing:
      max_latency: 250ms
      error_budget: 0.5%

security:
  jwt:
    issuer: "https://auth.iaros.ai"
    audience: ["gateway.prod", "monitoring"]
    required_claims:
      - "https://iaros.ai/roles"
      - "https://iaros.ai/pricing_tier"
  headers:
    strict_transport_security: "max-age=63072000; includeSubDomains; preload"
    content_security_policy: "default-src 'self'; frame-ancestors 'none'"
  cors:
    allowed_origins: ["https://*.iaros.ai"]
    methods: ["GET", "POST", "OPTIONS"]
    max_age: 600

monitoring:
  metrics_endpoint: "/telemetry"
  sampling_rate: 100%
  export_interval: 30s
  dimensions:
    - "service_version"
    - "geo_region"
    - "client_type"
  alerts:
    - name: "high_error_rate"
      condition: "rate(http_requests_total{status!~'2..'}[5m]) > 0.1"
    - name: "latency_spike"
      condition: "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) > 1.5"

compliance:
  gdpr:
    data_retention: "30d"
    right_to_be_forgotten: true
  ccpa:
    opt_out_endpoint: "/privacy/ccpa"
  pci:
    isolated_routing_group: "payments"

# Fallback Policies
fallback:
  use_cached_response: true
  cache_expiry: "5m"
